// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_type::Message;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `message`.
///
/// Obtain a handle from the [`MessageTableAccess::message`] method on [`super::RemoteTables`],
/// like `ctx.db.message()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.message().on_insert(...)`.
pub struct MessageTableHandle<'ctx> {
    imp: __sdk::TableHandle<Message>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `message`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MessageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MessageTableHandle`], which mediates access to the table `message`.
    fn message(&self) -> MessageTableHandle<'_>;
}

impl MessageTableAccess for super::RemoteTables {
    fn message(&self) -> MessageTableHandle<'_> {
        MessageTableHandle {
            imp: self.imp.get_table::<Message>("message"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MessageInsertCallbackId(__sdk::CallbackId);
pub struct MessageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MessageTableHandle<'ctx> {
    type Row = Message;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Message> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MessageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MessageInsertCallbackId {
        MessageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MessageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MessageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MessageDeleteCallbackId {
        MessageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MessageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MessageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MessageTableHandle<'ctx> {
    type UpdateCallbackId = MessageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MessageUpdateCallbackId {
        MessageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MessageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `message`,
/// which allows point queries on the field of the same name
/// via the [`MessageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.message().id().find(...)`.
pub struct MessageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Message, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MessageTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `message`.
    pub fn id(&self) -> MessageIdUnique<'ctx> {
        MessageIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MessageIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Message> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Message>("message");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Message>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Message>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Message`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait messageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Message`.
    fn message(&self) -> __sdk::__query_builder::Table<Message>;
}

impl messageQueryTableAccess for __sdk::QueryTableAccessor {
    fn message(&self) -> __sdk::__query_builder::Table<Message> {
        __sdk::__query_builder::Table::new("message")
    }
}
